version: '3.8'

services:
  mysql-container:  # Match hostname in development.py
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "1111"  # Same as in development.py
      MYSQL_DATABASE: "ggulgguk"
    ports:
      - "3306:3306"
    networks:
      - my-network    
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  flask-app:
    build: .
    ports:
      - "5000:5000"
    networks:
      - my-network    
    environment:
      APP_CONFIG_FILE: "/app/config/development.py"
    depends_on:
      mysql-container:
        condition: service_healthy
networks:
  my-network:
    driver: bridge    
volumes:
  mysql_data:
